package hr.fer.edugame.constants

const val KEY_USER = "user"
const val KEY_LETTERS = "letters"
const val KEY_WORD = "word"
const val KEY_WANTED_NUMBER = "wantedNumber"
const val KEY_FINAL_NUMBER = "finalNumber"
const val KEY_TIME = "time"
const val FIREBASE_USERS_ONLINE_CHILD = "usersOnline"
const val FIREBASE_GAMES_CHILD = "games"
const val FIREBASE_GAME_POINTS = "points"
const val FIREBASE_RANK_LIST = "rankList"
const val FIREBASE_RANK_SINGLE_PLAYER = "rankSinglePlayer"
const val FIREBASE_RANK_MULTIPLAYER = "rankMultiplayer"
const val FIREBASE_CALCULATED_NUMBER = "calculatedNumber"
const val FIREBASE_NUMBERS_GAME = "numberGame"
const val FIREBASE_WANTED_NUMBER = "wantedNumber"
const val FIREBASE_WORDS_GAME = "wordsGame"
const val FIREBASE_GENERATED_LETTERS = "generatedLetters"
const val FIREBASE_FINAL_WORD = "finalWord"
const val FIREBASE_REACHED_FIFTY_POINTS = "reachedFifty"
